# Generated by Django 3.0.4 on 2020-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='division',
            field=models.CharField(choices=[('SE/A', 'SE/A'), ('SE/B', 'SE/B'), ('TE/A', 'TE/A'), ('TE/B', 'TE/B')], default='', max_length=30),
        ),
    ]
